# Generated by Django 6.0.7 on 2026-07-25 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('job', 'job'), ('internship', 'internship'), ('attachment', 'attachment'), ('study_abroad', 'study abroad')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('requirements', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'manual'), ('ai', 'ai')], default='manual', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('education_level', models.CharField(blank=True, max_length=255)),
                ('qualifications', models.TextField(blank=True)),
                ('interest_tags', models.JSONField(blank=True, default=list)),
                ('desired_types', models.JSONField(blank=True, default=list)),
                ('auth_provider', models.CharField(choices=[('local', 'local'), ('google', 'google')], default='local', max_length=20)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.opportunity')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('seen', 'seen'), ('saved', 'saved'), ('applied', 'applied')], default='seen', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.opportunity')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.userprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('profile', 'opportunity')},
            },
        ),
    ]
