# Generated by Django 6.0.7 on 2026-07-25 16:16

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def map_verified_to_status(apps, schema_editor):
    Opportunity = apps.get_model("core", "Opportunity")
    now = timezone.now()
    for opp in Opportunity.objects.all():
        if opp.verified:
            opp.status = "live"
            if not opp.last_verified_at:
                opp.last_verified_at = now
        else:
            opp.status = "unverified"
        opp.save(update_fields=["status", "last_verified_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eight_categories_intent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-roi_score', '-updated_at']},
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='type',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='source',
        ),
        migrations.AddField(
            model_name='match',
            name='eligibility_pass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='roi_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='match',
            name='surfaced_as',
            field=models.CharField(choices=[('listing', 'listing'), ('move', 'move')], default='listing', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='why_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='deadline_tz',
            field=models.CharField(blank=True, default='Africa/Nairobi', max_length=64),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='eligibility_rules',
            field=models.JSONField(blank=True, default=dict, help_text='{citizenship[], location[], deadline, budget_required}'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='roi_inputs',
            field=models.JSONField(blank=True, default=dict, help_text='{effort_estimate, value_estimate} — formula varies by category'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, help_text='platform + original listing id for dedup', max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source_type',
            field=models.CharField(choices=[('api', 'api'), ('scrape', 'scrape'), ('pdf_parse', 'pdf_parse'), ('social_signal', 'social_signal'), ('manual', 'manual')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('live', 'live'), ('expired', 'expired'), ('unverified', 'unverified')], db_index=True, default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ambition_vector',
            field=models.JSONField(blank=True, default=dict, help_text='{inferred_categories: [], confidence_scores: {}}'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hard_constraints',
            field=models.JSONField(blank=True, default=dict, help_text='{citizenship, location, budget, visa_status}'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='readiness_vector',
            field=models.JSONField(blank=True, default=dict, help_text='{career_stage, time_availability, course_load}'),
        ),
        migrations.AlterField(
            model_name='match',
            name='state',
            field=models.CharField(choices=[('seen', 'seen'), ('saved', 'saved'), ('applied', 'applied'), ('dismissed', 'dismissed')], default='seen', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='verified',
            field=models.BooleanField(default=False, help_text='Legacy flag; prefer status=live for surfacing'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='why_summary',
            field=models.TextField(blank=True, help_text='Canonical opportunity-level why blurb; Match.why_summary is per-user'),
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('intro_message', 'intro_message'), ('follow_up', 'follow_up'), ('cold_outreach_draft', 'cold_outreach_draft'), ('networking_target', 'networking_target')], max_length=32)),
                ('target_person_or_org', models.CharField(max_length=255)),
                ('suggested_action_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='core.userprofile')),
                ('trigger_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='core.opportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('bookmark', 'bookmark'), ('dismiss', 'dismiss'), ('linger', 'linger'), ('apply', 'apply')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_logs', to='core.opportunity')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_logs', to='core.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RunPython(map_verified_to_status, migrations.RunPython.noop),
    ]
