# Generated by Django 6.0.7 on 2026-07-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_compass_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text="Short self-description in the user's own words."),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo_data',
            field=models.TextField(blank=True, help_text='Optional profile photo as a compressed data URL (private).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pronouns',
            field=models.CharField(blank=True, help_text='Optional pronouns set by the user; never inferred.', max_length=64),
        ),
    ]
