# Generated by Django 6.0.7 on 2026-07-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_identity_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pronouns',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, help_text='Optional: male | female | prefer_not. Never inferred from name or photo.', max_length=32),
        ),
    ]
