# Generated by Django 6.0.7 on 2026-07-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_source_url_ingestion_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, help_text='Optional: male | female. Blank until the user chooses; never inferred.', max_length=32),
        ),
    ]
